# Use an official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Environment variables (if not passed via docker-compose or CLI)
ENV MONGODB_URI=${MONGODB_URI}
ENV EMAIL_PASS=${EMAIL_PASS}
ENV SESSION_SECRET=${SESSION_SECRET}

# Start the application
CMD ["npm", "start"]


# docker run -p 3000:3000 `
#    -e MONGODB_URI="mongodb+srv://youssefalaaalfahl:You01064167295@cluster0.pj7i39k.mongodb.net/shop?retryWrites=true&w=majority" `
#    -e EMAIL_PASS="zatbhvulzmncofng" `
#    -e SESSION_SECRET="mySecret" `
#    ecommerceapp